# Generated by Django 5.2.6 on 2025-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_alter_lessons_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='sub_id',
            field=models.ManyToManyField(blank=True, to='edu.subjects', verbose_name='Предметы'),
        ),
    ]
