# Generated by Django 5.2.6 on 2025-11-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_alter_classes_sub_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='lesson_id',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='edu.lessons', verbose_name='Уроки'),
        ),
    ]
